### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by joelkoen** [beacondb/beacondb#5]
https://github.com/mjaakko/NeoStumbler/issues/79#issuecomment-2171955526

I've had issues with my IPv6 changing/dropping out, but that was a while ago so I'll try enabling it again.

**Comment by joelkoen** [comment]
I've updated my config and IPv6 seems to be working from inside my network but my hotspot doesn't support ipv6 so I can't check it works from outside.

@lucasmz-dev when you get a chance could you help me check my setup? `curl -6 https://beacondb.net/`

**Comment by lucasmz-dev** [comment]
seems to be working :)

![image](https://github.com/beacondb/beacondb/assets/55422065/b7f041a1-2e21-488d-a22f-561ea4da82cc)

using IPvFoo on Firefox and going to the website also

good job!!!! <3

**Comment by lucasmz-dev** [comment]
Well the first time I opened on Firefox it used IPv4 but after a full refresh it went to IPv6 so might've just been DNS caching.

**Comment by joelkoen** [comment]
Awesome, thanks for the help testing!
