### ISSUE TITLE
[Question] Moving to Codeberg

### ISSUE THREAD

**Issue by EchedelleLR** [beacondb/beacondb#7]
Since this is a community project, I would be concerned about this being moved there and leaving this as a mirror.

**Comment by joelkoen** [comment]
I agree that this project is better suited to being hosted on a service like Codeberg. I've pushed to [this repository](https://codeberg.org/beacondb/beacondb) and will slowly start using that as the "main" place for development.

**Comment by EchedelleLR** [comment]
Thx 💙

**Comment by joelkoen** [comment]
This repository is now configured as a push mirror, and I've added various links on GitHub and the beaconDB website to Codeberg. Thanks!
