### ISSUE TITLE
[Feature request] Coverage map

### ISSUE THREAD

**Issue by Hoerli1337** [beacondb/beacondb#9]
Hi!
It's really great of you to have started such a project.

It would be great if there was a coverage map.
That way you can see which parts of the world have not yet been measured, just like with MLS, for example.

Tower Collector also provides the location data where the measurement was taken,
This could be used for the map.

**Comment by EchedelleLR** [comment]
That is really something.

I live in some middle area in the Canary Islands and a few years ago when MLS was a thing, I used to go to uncovered places in the mountains and contribute back but at some point the data was removed or so.

Maybe was when the suing hit them or similar and I had to cover the area again later.

**Comment by joelkoen** [comment]
Moved to Codeberg: https://codeberg.org/beacondb/beacondb/issues/2
